# Docker
- task: VSTest@3
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\*test*.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'
    runOnlyImpactedTests: true
    runInParallel: true
    runTestsInIsolation: true
    codeCoverageEnabled: false
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        buildContext: $(Build.SourcesDirectory)
        dockerfile: $(Build.SourcesDirectory)/ApiGatewayes/OcelotApiGW/Dockerfile
        tags: |
          $(tag)
